backend/controllers/VideosController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Videos;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * VideosController implements the CRUD actions for Videos model.
 */
class VideosController extends Controller
{
    /**
     * {@inheritdoc}
     */

    //  'access' asegura que los usuarios que puedan acceder a los videos
    //  forzozamente tengan que estar logeados y en una sesion activa
    //  de lo contrario, los manda directo a la pantalla de Login
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                    'allow' => true,
                    'roles' => ['@']
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Videos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Videos::find()->creator(Yii::$app->user->id),
        ]);

        //La funcion creator, la creamos desde la clase Video Query
        //find es un método que encontramos en el modelo de Video

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Videos model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Videos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Videos();

        $model->video = UploadedFile::getInstanceByName('video'); 

        if (Yii::$app->request->isPost && $model->save()) {
            return $this->redirect(['update', 'id' => $model->video_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Videos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $model->thumbnail = UploadedFile::getInstanceByName('thumbnail');


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->video_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Videos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Videos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Videos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Videos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/layouts/_header.php
<?php
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
//UI Widgets
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-lg navbar-light bg-light shadow-sm']
    ]);
    $menuItems = [
        ['label' => 'Create', 'url' => ['/videos/create']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
             'label' => 'Logout ('.Yii::$app->user->identity->username.')',
             'url' => ['/site/logout'],
             'linkOptions' => [
                 'data-method' => 'post'
             ] 
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav  ml-auto'],
        'items' => $menuItems,
    ]);

    NavBar::end();
    ?>

backend/views/layouts/_sidebar.php
<aside class="shadow">

<?php echo \yii\bootstrap4\Nav::widget([

'options' => [

    'class' => 'd-flex flex-column nav-pills'

],

'items' => [

    [
        'label' => 'Dashboard',
        'url' => ['/site/index']

    ],

    [
        'label' => 'Videos',
        'url' => ['/videos/index']
    ],

    [
        'label' => 'Comments',
        'url' => ['/comment/index']
    ]

]

]) ?>

</aside>

backend/views/layouts/auth.php
<?php
use common\widgets\Alert;
use backend\assets\AppAsset;

AppAsset::register($this);
$this->beginContent('@backend/views/layouts/base.php')
?>
        <main class="d-flex">

            <div class="content-wrapper p-3">

                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </main>
<?php $this->endContent() ?>

backend/views/layouts/base.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;

use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        rel="stylesheet">
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>

    <div class="wrap h-100 d-flex flex-column">
        <div class="wrap h-100 d-flex flex-column">
            <?php echo $this->render('_header') ?>

            <?php echo $content ?>
        </div>

        <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

use common\widgets\Alert;
use backend\assets\AppAsset;

AppAsset::register($this);
$this->beginContent('@backend/views/layouts/base.php')
?>
<main class="d-flex">
    <?php echo $this->render('_sidebar') ?>

    <div class="content-wrapper p-3">

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<?php $this->endContent() ?>