frontend/controllers/VideoController.php
<?php

namespace frontend\controllers;

use yii\data\ActiveDataProvider;
use yii\web\Controller;
use common\models\Videos;
use yii\web\NotFoundHttpException;
use common\models\VideoView;
use common\models\VideoLike;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class VideoController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['like', 'dislike'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
                    ],
                    'verb' => [
                        'class' => VerbFilter::class,
                        'actions' => [
                            'like' => ['post'],
                            'dislike' => ['post'],
                        ]
                    ]
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Videos::find()->published()->latest()
        ]);
       return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    public function actionView($id)
    {
        $this->layout = 'auth';
        
        
        $video = $this->findVideo($id);
        $video = Videos::findOne($id);
        if (!$video){
            throw new NotFoundHttpException("Video does not exists.");
        }

        $videoView = new VideoView();
        $videoView->video_id = $id;
        $videoView->user_id = \Yii::$app->user->id;
        $videoView->created_at = time();
        $videoView->save();

        return $this->render('view',[
            'model' => $video
        ]);

    }

    public function actionLike($id)
    {
        $video = $this->findVideo($id);
        $userId = \Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()
        ->userIdVideoId($userId, $id)
        ->one();

        
        if(!$videoLikeDislike) {  
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_LIKE);
        }else if($videoLikeDislike->type == VideoLike::TYPE_LIKE ){
            $videoLikeDislike->delete();
        } else {
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_LIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);

    }

    public function actionDislike($id)
    {
        $video = $this->findVideo($id);
        $userId = \Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()
        ->userIdVideoId($userId, $id)
        ->one();

        
        if(!$videoLikeDislike) {  
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_DISLIKE);
        }else if($videoLikeDislike->type == VideoLike::TYPE_DISLIKE){
            $videoLikeDislike->delete();
        } else {
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_DISLIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);

    }

    protected function findVideo($id)
    {
        $video = Videos::findOne($id);
        if (!$video){
            throw new NotFoundHttpException("Video does not exists.");
        }
        return $video;
    }

    protected function saveLikeDislike($videoId, $userId, $type)
    {
            $videoDislike = new VideoLike();
            $videoDislike->video_id = $videoId;
            $videoDislike->user_id = $userId;
            $videoDislike->type = $type;
            $videoDislike->created_at = time();
            $videoDislike->save();
    }

}

?>

frontend/views/layouts/_header.php
<?php
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
//UI Widgets
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-lg navbar-light bg-light shadow-sm']
    ]);
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Sign up', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
             'label' => 'Logout ('.Yii::$app->user->identity->username.')',
             'url' => ['/site/logout'],
             'linkOptions' => [
                 'data-method' => 'post'
             ] 
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav  ml-auto'],
        'items' => $menuItems,
    ]);

    NavBar::end();
    ?>

frontend/views/layouts/_sidebar.php
<aside class="shadow">

<?php echo \yii\bootstrap4\Nav::widget([

'options' => [

    'class' => 'd-flex flex-column nav-pills'

],

'items' => [

    [
        'label' => 'Home',
        'url' => ['/video/index']

    ],

    [
        'label' => 'History',
        'url' => ['/videos/history']
    ],

    

]

]) ?>

</aside>

frontend/views/layouts/auth.php
<?php
use common\widgets\Alert;


$this->beginContent('@frontend/views/layouts/base.php')
?>
        <main class="d-flex">

            <div class="content-wrapper p-3">

                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </main>
<?php $this->endContent() ?>

frontend/views/layouts/base.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use frontend\assets\AppAsset;
use yii\helpers\Html;

use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
// NOTA: Es importante agregar el assetManager en el archivo
// main.php de la carpeta config para que se pueda leer el css 
// que tenemos en la carpeta web/css, al igual si agregamos un
// archivo .js
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        rel="stylesheet">
    <?php $this->head() ?>
</head>

<body>
    <?php $this->beginBody() ?>

    <div class="wrap h-100 d-flex flex-column">
        <div class="wrap h-100 d-flex flex-column">
            <?php echo $this->render('_header') ?>

            <?php echo $content ?>
        </div>

        <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

use common\widgets\Alert;

$this->beginContent('@frontend/views/layouts/base.php')
?>
<main class="d-flex">
    <?php echo $this->render('_sidebar') ?>

    <div class="content-wrapper p-3">

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<?php $this->endContent() ?>