frontend/controllers/ChannelController.php
<?php

namespace frontend\controllers;

use common\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;

class ChannelController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['suscribe'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
        ];
    }

    public function actionView($username)
    {
       $channel = $this->findChannel($username);

        return $this->render('view', [
            'channel' => $channel
        ]);
    }

    public function actionSuscribe($username)
    {
        $channel = $this->findChannel($username);

    }

    protected function findChannel($username)
    {
        $channel = User::findByUsername($username);
        if(!$channel){
            throw new NotFoundHttpException("Channel does not exist.");
        }
        return $channel;
    }


}




?>

frontend/views/channel/_suscribe.php
<?php

use yii\helpers\Url;

?>

<a class="btn btn-danger" href="<?php echo Url::to(['channel/suscribe', 
        'username' => $channel->username]) ?>" 
        data-method="post">
        Suscribe <i class="far fa-bell"></i>
</a>9

frontend/views/channel/view.php
<?php

/** @var $channel \commmon\models\User */

use yii\helpers\Url;
use yii\widgets\Pjax;

?>
<div class="jumbotron">
    <h1 class="display-4"><?php echo $channel->username ?></h1>
    <hr class="my-4">
    <?php Pjax::begin()?>
        <?php echo $this->render('_suscribe',[
            'channel' => $channel
        ]) ?>
    <?php Pjax::end()?>
</div>